PYTHON_KEYWORDS = {
    "learn": ":learn",
    "advanced": "Advanced",
    "class": "Classes",
    "classes": "Classes",
    "comments": "Comments",
    "control+flow": "Control_Flow",
    "functions": "Functions",
    "function": "Functions",
    "modules": "Modules",
    "primitives": "Primitive_Datatypes_and_Operators",
    "datatypes": "Primitive_Datatypes_and_Operators",
    "operators": "Primitive_Datatypes_and_Operators",
    "variables": "Variables_and_Collections",
    "variable": "Variables_and_Collections",
    "collection": "Variables_and_Collections",
    "collections": "Variables_and_Collections",
    "doc": "doc",
    "func": "func",
    "hello": "hello",
    "lambda": "lambda",
    "loop": "loops",
    "loops": "loops",
    "recursion": "recursion",
}

PYTHON_COMMON_KEYWORDS = [
    "Advanced",
    "Classes",
    "Collections",
    "Comments",
    "Control Flow",
    "Datatypes",
    "Doc",
    "Functions",
    "Lambda",
    "Loops",
    "Modules",
    "Operators",
    "Primitive",
    "Recursion",
    "Variables",
]
